#!/usr/bin/env python3
from pathlib import Path
import json

root = Path(__file__).resolve().parent.parent
order = [
    "src/glimmer/backend.lg",
    "src/glimmer/ratom.lg",
    "src/glimmer/core.lg",
    "src/glimmer_gtk/core.lg",
    "src/gtt/config.lg",
    "src/gtt/provider.lg",
    "src/gtt/provider/clockify.lg",
    "src/gtt/provider/kimai.lg",
    "src/gtt/provider/mock.lg",
    "src/gtt/application.lg",
    "src/gtt/state.lg",
    "src/gtt/actions.lg",
    "src/gtt/view.lg",
    "src/gtt/format.lg",
]
out = root / "cmd/gtt-letgo-gtk/sources_generated.go"
lines = ["// Code generated by scripts/embed-sources.py; DO NOT EDIT.", "package main", "", "var embeddedSources = []string{"]
for relative in order:
    source = (root / relative).read_text()
    lines.append(f"\t{json.dumps(source)},")
lines.extend(["}", ""])
out.write_text("\n".join(lines))
